daysUntilStale: 60
daysUntilClose: 30
# Issues with these labels will never be considered stale.
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale.
staleLabel: stale
# Comment to post when marking an issue as stale.
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
