require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false
production = ENV["PRODUCTION"] == "1"

#enable for firebase
# pod 'Firebase', :modular_headers => true
# pod 'FirebaseCore', :modular_headers => true
# pod 'FirebaseCoreInternal', :modular_headers => true
# pod 'GoogleUtilities', :modular_headers => true

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
#     end
#   end
# end

target 'AnalyticsReactNativeExample' do
  config = use_native_modules!
  
  
# Flags change depending on the env values.
flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :production => production,
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
)
  
  # Pods for AnalyticsReactNativeExample
  pod 'sovran-react-native', :path => '../../packages/sovran'
  pod 'segment-analytics-react-native', :path => '../../packages/core'
  # Pods for Plugins
  pod 'segment-analytics-react-native-plugin-idfa', :path => '../../packages/plugins/plugin-idfa'

  post_install do |installer|
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(SDKROOT)/usr/lib/swift', '$(inherited)']
        end
      end
      aggregate_target.user_project.save
     end
  end
end
