require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
#     end
#   end
# end

target 'AnalyticsReactNativeExample' do
  config = use_native_modules!

 # Flags change depending on the env values.
flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  # Pods for AnalyticsReactNativeExample
  pod 'segment-analytics-react-native', :path => '../../packages/core'
  # Pods for Plugins
  pod 'segment-analytics-react-native-plugin-idfa', :path => '../../packages/plugins/plugin-idfa'

  # use_flipper!({ 'Flipper' => '0.125.0', 'Flipper-Folly' => '~> 2.6', 'Flipper-RSocket' => '~> 1.4', "Flipper-DoubleConversion" => "1.1.7" })
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
      end
    end
    # flipper_post_install(installer)
  end

end
