source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

gem 'cocoapods', '~> 1.13'
gem 'activesupport', '~> 8.0.4', '>= 8.0.4.1'
gem 'rexml', '>= 3.2.7'
