name: CI

on:
  push:
    branches: [master, beta]
  pull_request:
    branches: [master, beta]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_URL }}

jobs:
  ci:
    name: Lint + Build + Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Artifactory OIDC Auth
        uses: ./.github/actions/artifactory-oidc
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
      - run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint (eslint)
        run: yarn lint
      - name: Lint (formatting)
        run: yarn format:check
      - name: Build
        run: yarn build
      - name: Typecheck
        run: yarn typecheck
      - name: Test
        run: yarn test

  commitlint:
    name: Commitlint
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Artifactory OIDC Auth
        uses: ./.github/actions/artifactory-oidc
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
      - run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Validate PR title
        run: echo "$PR_TITLE" | yarn commitlint
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
