name: Release

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - dry-run
          - beta
          - production

concurrency:
  group: release
  cancel-in-progress: true

env:
  ARTIFACTORY_URL: ${{ vars.ARTIFACTORY_URL }}

jobs:
  ci:
    name: Lint + Build + Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Artifactory OIDC Auth
        uses: ./.github/actions/artifactory-oidc
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
      - run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint (eslint)
        run: yarn lint
      - name: Lint (formatting)
        run: yarn format:check
      - name: Build
        run: yarn build
      - name: Typecheck
        run: yarn typecheck
      - name: Test
        run: yarn test

  release-dryrun:
    name: Release (dry-run)
    if: inputs.type == 'dry-run'
    needs: [ci]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Artifactory OIDC Auth
        uses: ./.github/actions/artifactory-oidc

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
      - run: corepack enable

      - name: Release (dry-run)
        run: |
          yarn install --immutable
          yarn build
          yarn multi-semantic-release --dry-run
        env:
          GH_TOKEN: ${{ github.token }}

  release-beta:
    name: Release (beta)
    if: inputs.type == 'beta'
    needs: [ci]
    runs-on: ubuntu-latest
    environment: Publish-Beta
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Artifactory OIDC Auth
        uses: ./.github/actions/artifactory-oidc

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
      - run: corepack enable

      - name: Release (beta)
        run: |
          yarn install --immutable
          yarn build
          yarn release
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_REF: refs/heads/${{ github.ref_name }}
          NPM_CONFIG_IGNORE_SCRIPTS: 'true'

  release-production:
    name: Release (production)
    if: inputs.type == 'production'
    needs: [ci]
    runs-on: ubuntu-latest
    environment: Publish
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Artifactory OIDC Auth
        uses: ./.github/actions/artifactory-oidc

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
      - run: corepack enable

      - name: Release (production)
        run: |
          yarn install --immutable
          yarn build
          yarn release
        env:
          GH_TOKEN: ${{ github.token }}
          NPM_CONFIG_IGNORE_SCRIPTS: 'true'

      - name: Update Apps
        run: |
          yarn install --no-immutable
          yarn --cwd examples/AnalyticsReactNativeExample install --no-immutable
