name: Release

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - dry-run
          - beta
          - production

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  ci:
    name: Lint + Build + Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.14.0
      - name: Install dependencies
        run: devbox run ci:install
      - name: Lint (eslint)
        run: devbox run lint
      - name: Lint (formatting)
        run: devbox run format-check
      - name: Build
        run: devbox run build
      - name: Typecheck
        run: devbox run typecheck
      - name: Test
        run: devbox run test

  e2e-tests:
    name: E2E Mobile Tests
    needs: [ci]
    if: inputs.type == 'beta' || inputs.type == 'production'
    uses: ./.github/workflows/e2e-mobile-tests.yml

  release-dryrun:
    name: Release (dry-run)
    if: inputs.type == 'dry-run'
    needs: [ci]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.14.0

      - name: Release (dry-run)
        run: devbox run release-dry-run
        env:
          GH_TOKEN: ${{ github.token }}

  release-beta:
    name: Release (beta)
    if: inputs.type == 'beta'
    needs: [ci, e2e-tests]
    runs-on: ubuntu-latest
    environment: Publish-Beta
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.14.0

      - name: Release (beta)
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          devbox run -e GITHUB_REF=refs/heads/$BRANCH_NAME release
        env:
          GH_TOKEN: ${{ github.token }}

  release-production:
    name: Release (production)
    if: inputs.type == 'production'
    needs: [ci, e2e-tests]
    runs-on: ubuntu-latest
    environment: Publish
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.14.0

      - name: Release (production)
        run: devbox run release
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Update Apps
        run: devbox run update-apps
